### PR TITLE
Adding T[_[_], _], T[_[_], _, _], T[_, _, _]

### PR DESCRIPTION
**Pull request by wheaties**
This will solve my immediate needs. Will look into solving for more types using either some boilerplate or what not.

### CODE REVIEW

**Comment by wheaties** [comment]
Looks like this has failed binary compatibility checks. MiMA?

**Comment by milessabin** [comment]
Yes, MiMa. It's OK to ignore warnings about methods not being in the old version, so just add the filters that have been suggested and you should be good.

**Comment by milessabin** [comment]
Also, could you reformat to match the rest of the codebase? Essentially two space indent and aggressive line breaking.

**Comment by milessabin** [comment]
Good stuff! Many thanks ... merging :-)

**Pull request merged**
