### PR TITLE
Scala 2.13.0-RC1 and other version bumps

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, the RC1 upgrade won't become mergeable until simulacrum becomes available, https://github.com/mpilquist/simulacrum/pull/132

**Comment by SethTisue** [comment]
tried this in the community build, but:

```
[export-hook] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/export-hook-241b8b523fd2f2203b96c7deecd64f5f41716d87/core/.jvm/target/scala-2.13.0-RC1/src_managed/main/export/exportGen.scala:6: not found: object macrocompat
[export-hook] [error] import macrocompat.bundle
[export-hook] [error]        ^
```

does macro-compat needs to be published for RC1? I had vaguely thought, not based on any real understanding, that if Shapeless doesn't need it anymore, it wouldn't be needed here anymore either?

**Comment by milessabin** [comment]
There's no macro-compat for 2.13.x, and TBQH I wasn't really planning to publish export-hook beyond 2.12.x either ... I consider it a failed experiment.

Are there any important users of it in the community build? If not, then I suggest just removing it.

**Comment by milessabin** [comment]
Hmm ... or maybe there _is_ a macro-compat for 2.13.x.

**Comment by larsrh** [comment]
> does macro-compat needs to be published for RC1? I had vaguely thought, not based on any real understanding, that if Shapeless doesn't need it anymore, it wouldn't be needed here anymore either?

@SethTisue macro-compat could be removed altogether after dropping 2.10 support in libraries.

**Comment by milessabin** [comment]
I've just published macro-compat 1.1.1 for 2.13.0-RC1.

Like I said, I consider export-hook a failed experiment, so I recommend the least-effort option here. Sticking with macro-compat is probably that for now.

**Comment by SethTisue** [comment]
> I wasn't really planning to publish export-hook beyond 2.12.x either ... I consider it a failed experiment.

export-hook is still in the cats build. can it be taken out? /cc @kailuowang

**Comment by kailuowang** [comment]
it's extensively used in alleycats, although there are no longer good reasons for it to remain so after kittens removed support for export-hook. Removing export-hook from alleycats has been at the back of my mind. Just created an issue. https://github.com/typelevel/cats/issues/2777

**Comment by milessabin** [comment]
@kailuowang I think that's the right thing to do.

I _will_ publish export for 2.13.0-RC1 though, as soon as simulacrum is published.

**Comment by milessabin** [comment]
Resolved on master and published.

**Pull request closed without merging**
