### PR TITLE
minimal reproduction of warts

### PR DESCRIPTION
**Pull request by fommil**
Reproduces #28

I don't feel a minimal reproduction is enough for this as it would be safer to enable all the warts to avoid regressions in the future.

This "bug" will be redundant if https://github.com/wartremover/wartremover/issues/215 is closed.

It might also be a good idea to use

```scala
scalacOptions it Test ++= Seq(
  "-Yno-imports",
  "-Yno-predef"
)
```

to ensure that the macros do not assume that the system imports are available (forcing the macro author to use FQN `_root_.` names everywhere)

### CODE REVIEW

**Comment by milessabin** [comment]
I'm not going to merge a PR which is designed to illustrate a bug in another project.

**Comment by fommil** [comment]
the ability to ignore or not ignore the bad code being emitted by these macros is neither here nor there. These macros are not adding explicit types, and `null` is being used.

**Comment by fommil** [comment]
example of your `alleycats.scala` test compiled with `-print`

```
  final class anon$3 extends Object with alleycats.Empty {
    final <synthetic> lazy private[this] var empty: Object = _;
    @volatile private[this] var bitmap$0: Boolean = _;
    private def empty$lzycompute(): Object = {
      anon$3.this.synchronized(if (anon$3.this.bitmap$0.unary_!())
        {
          anon$3.this.empty = (anon$3.this.a$2.apply(): Object);
          anon$3.this.bitmap$0 = true
        });
      anon$3.this.a$2 = null;
      anon$3.this.empty
    };
    <stable> <accessor> lazy def empty(): Object = if (anon$3.this.bitmap$0.unary_!())
      anon$3.this.empty$lzycompute()
    else
      anon$3.this.empty;
    <synthetic> <paramaccessor> private[this] val a$2: Function0 = _;
    def <init>(a$2: Function0): <$anon: alleycats.Empty> = {
      anon$3.this.a$2 = a$2;
      anon$3.super.<init>();
      ()
    }
  };
  abstract trait EmptyInstances$LowPriority extends Object;
  final class anon$4 extends Object with alleycats.Empty {
    def empty(): Object = anon$4.this.$outer.empty();
    <synthetic> <paramaccessor> <artifact> private[this] val $outer: alleycats.EmptyK = _;
    def <init>($outer: alleycats.EmptyK): <$anon: alleycats.Empty> = {
      if ($outer.eq(null))
        throw null
      else
        anon$4.this.$outer = $outer;
      anon$4.super.<init>();
      ()
    }
  };
```

**Comment by fommil** [comment]
`-Xprint:typer` is more revealing, e.g. for your `alleycats.scala` example

```
    object exports extends scala.AnyRef {
      def <init>(): alleycats.Bar.exports.type = {
        exports.super.<init>();
        ()
      };
      import scala.language.experimental.macros;
      @scala.reflect.macros.internal.macroImpl(`macro`("macroEngine" = "v7.0 (implemented in Scala 2.11.0-M8)", "isBundle" = true, "isBlackbox" = false, "className" = "export.ExportsImplExpr", "methodName" = "exportsImpl00", "signature" = List(List(0, 1, 2, 3)))[alleycats.Bar, fresh$macro$16, fresh$macro$17, export.Export5]) implicit <macro> def alleycats$Bar$anonimplicit$0[fresh$macro$9[fresh$macro$13, fresh$macro$14] >: [fresh$macro$13, fresh$macro$14]alleycats.Bar[fresh$macro$13,fresh$macro$14] <: [fresh$macro$13, fresh$macro$14]Any, fresh$macro$16, fresh$macro$17]: export.Export5[fresh$macro$9[fresh$macro$16,fresh$macro$17]] = new export.ExportsImplExpr(null).exportsImpl00[alleycats.Bar, fresh$macro$16, fresh$macro$17, export.Export5]
    };
```

indeed it seems that many invocations of `new export.ExportsImplExpr` are with the `null` parameter. I'll try to see if I can add the suppresswarning annotation to that.

**Comment by fommil** [comment]
I pushed a commit that adds the warning suppression on the `def` with `null` in it, but it isn't being ignored.

**Comment by fommil** [comment]
I give up, it looks like the `$mods` need to have the suppress warnings added to them and that seems very tricky.

People will just have to add the manual warnings like I do if they want to have wartremover in the rest of their project.

**Pull request closed without merging**
